### ISSUE TITLE
FE Todo list 

### ISSUE THREAD

**Issue by YunHanKIM** [codestates-seb/abc02_003#1]
## 만들고자 하는 페이지
1. 로그인 페이지 화면 - mj
2. 회원가입 페이지 화면 - mj
3. 메인 페이지 화면 - yh
4. 게시판 페이지 화면 - sw

### 회원
1. [ ] 로그인 / 로그아웃
2. [ ] 회원가입

### 메인
1. [ ] 메인 페이지 헤더
2. [ ] 메인 페이지 푸터
3. [ ] 메인 화면 구성

### 게시판
1. [ ] 게시글 리스트 형태로 보이게
2. [ ] 게시글 글쓰기 버튼
3. [ ] 게시글 수정 버튼
4. [ ] 게시글 삭제 버튼

## 예상 작업시간
~ 1 / 3 스프린트1 회고 시간 까지 화면 구성하기
